### PR TITLE
CHECKPOINT 1 REVIEW

### PR DESCRIPTION
**Pull request by andela-fopara**
**What does this PR do?**
It fixes the applications travis error, and its also completes the app feature.

**Description of Task to be Completed**
Make the project to be able to handle multiple file selections and create appropriate index, show error modals for empty files, files that are not valid json objects, or ill-formated json files. It also remodels the ui component placements for ease of usage. Integrate Travis CI, HoundCI, Coveralls, Eslint using Airbnb.

Created this PR because I made a mistake in which branch to use as base and Head when creating other PRs

**How Should this be manually tested?**
npm start

### CODE REVIEW

**Comment by andela-kakpobome** [comment]
@andela-fopara you should use a markdown list to outline the issues you solved with the PR

**Comment by andela-kakpobome** [comment]
@andela-fopara there are no files to review here, I'm not sure what you expect me to do.

**Comment by andela-fopara** [comment]
Ok I will use the markdown list.

**Comment by andela-fopara** [comment]
For the files to review, there are only four files changed in the PR, they
are the files you said you only want to see, I don't understand what you
mean again by there is no files to review? Please how do you mean?

**Comment by andela-fopara** [comment]
Ok, I understand, even though there are four files changed, the files are
not there because the files shown are marked in red background. I will fix
that. And do the markdown list.

**Comment by andela-fopara** [comment]
Please, I tried switching the branches I used as base for head to actually achieve the desired effect, but github told me nothing to compare. I think the only option left is to edit my commit history and I am not even sure if it will work. What do you advice I do?

**Comment by andela-fopara** [comment]
Closed basing was wrong and no files was changed.

**Pull request closed without merging**
